//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCCReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixVersionRecord
    {
        public int FixVersionID { get; set; }
        public string FixVersionName { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public Nullable<int> RelatedFixVersionID { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
    }
}
