//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCCReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public Nullable<int> RelatedNoteID { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string Note1 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> EditedUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    }
}
