//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCCReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpcomingTask
    {
        public int TicketID { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Requester { get; set; }
        public string Pendingwith { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
