//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCCReportingTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.FixVersionRecords = new HashSet<FixVersionRecord>();
            this.Notes1 = new HashSet<Note>();
        }
    
        public int WorkItemID { get; set; }
        public Nullable<int> DevopsItemID { get; set; }
        public string Summary { get; set; }
        public string Type { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Assignee { get; set; }
        public Nullable<System.DateTime> ExpectedReleaseDate { get; set; }
        public string Fixversion { get; set; }
        public string Notes { get; set; }
        public string PendingWith { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public string ProjectName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixVersionRecord> FixVersionRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
    }
}
